# Generated by Django 5.1 on 2024-09-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nucleo',
            name='predio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
