# Generated by Django 5.1 on 2024-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0004_alter_nucleo_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleo',
            name='predio',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
